config/routes.rb
EgnaRails::Application.routes.draw do
  root 'projects#index'
  resources :projects

  get 'about' => 'static#about', as: :about
  get 'contact' => 'static#contact', as: :contact

end

app/models/gallery.rb
class Gallery < ActiveRecord::Base
end

app/models/project.rb
class Project < ActiveRecord::Base
  has_one :gallery
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  def index
    @projects = Project.all
  end

  def show
  end

  def new
    @project = Project.new
  end

  def edit
  end

  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render action: 'show', status: :created, location: @project }
      else
        format.html { render action: 'new' }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params[:project]
    end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def about
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/layouts/_footer.html.erb
<footer>
  some stuff here
</footer>

app/views/layouts/_header_nav.html.erb
<nav id="header-nav">
  <h1 class="logo"><%= link_to "Jai-Lee Egna or Something", root_path %></h1>
  <ul class="nav-links">
    <li><%= link_to("Projects", projects_path) %></li>
    <li><%= link_to("About", about_path) %></li>
    <li><%= link_to("Contact", contact_path) %></li>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <div id="egna-app">

      <%= render 'layouts/header_nav' %>
      <div id="main-content">
        <%= yield %>
      </div>
      <%= render 'layouts/footer' %>

    </div>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<div id="projects-index">
  <h2>Projects</h2>

  <ul class="projects small-block-grid-3">
    <% @projects.each do |project| %>
      <li>
        <a href="<%= url_for project %>">
          <div class="project-thumbnail">
            <img src="<%= project.thumbnail_filename %>" />
          </div>
          <div class="project-title">
            <h3><%= project.title %></h3>
          </div>
        </a>
      </li>
    <% end %>
  </ul>
</div>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<div id="project">
  <p id="notice"><%= notice %></p>

  <div class="project-images">
    <ul class="small-block-grid-1">
      <% @project.gallery.image_filenames.each do |image_filename|  %>
        <li><img src="<%= image_filename %>" /></li>
      <% end %>
    </ul>
  </div>

  <div class="project-information">
    <h2><%= @project.title %></h2>
    <ul>
      <li>client: <%= @project.client %></li>
      <li>description: <%= @project.description %></li>
    </ul>
  </div>
</div>